"""Probe stale cross-file rejection and fresh custom scip-go mapping on Go bytes."""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any


SPIKE_ROOT = Path(__file__).resolve().parents[1]


def sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def run(args: argparse.Namespace) -> dict[str, Any]:
    clean_root = args.clean_root.resolve(strict=True)
    fixture = args.fixture.resolve(strict=True)
    code_ir_root = args.code_ir_root.resolve(strict=True)
    binary = args.scip_go_binary.resolve(strict=True)
    work = args.work_dir.resolve()
    if work.exists():
        raise ValueError("freshness work directory must not already exist")
    work.mkdir(parents=True)
    dirty_root = work / "dirty"
    shutil.copytree(clean_root, dirty_root)

    sys.path.insert(0, str(SPIKE_ROOT))
    from scripts.scip_spike import digest, range_bytes, selected

    paths = selected("go")[2]
    clean_lane = clean_root / "go"
    dirty_lane = dirty_root / "go"
    source_before = digest(clean_lane, paths)
    reference_path = dirty_lane / "internal/selection/validator.go"
    reference_sha_before = sha256_file(reference_path)
    target_path = dirty_lane / "internal/discovery/state.go"
    source = target_path.read_text()
    marker = "return ok\n"
    if source.count(marker) != 1:
        raise ValueError("expected one frozen WorkflowState.Contains return statement")
    target_path.write_text(source.replace(marker, 'return ok && workflowID != "dirty-probe"\n', 1))
    source_after = digest(dirty_lane, paths)
    reference_sha_after = sha256_file(reference_path)
    if source_before == source_after or reference_sha_before != reference_sha_after:
        raise ValueError("dirty edit did not isolate the cross-file target source")

    shutil.copyfile(fixture / "manifest.json", dirty_lane / "manifest.json")
    (dirty_root / "syntax-ir-go.json").unlink(missing_ok=True)
    module_file = code_ir_root / "dist/engine/code-ir/index.js"
    export = subprocess.run(
        [
            "node",
            str(SPIKE_ROOT / "scripts/export_syntax_ir.mjs"),
            str(dirty_root),
            str(module_file),
            str(fixture.parent),
            "go",
        ],
        cwd=SPIKE_ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    if export.returncode != 0:
        raise RuntimeError(export.stderr or export.stdout)

    inventory_path = work / "dirty-source-inventory.json"
    subprocess.run(
        [
            "go", "run", str(SPIKE_ROOT / "scripts/go_ir_source_inventory.go"),
            "--fixture", str(dirty_lane), "--output", str(inventory_path),
        ],
        cwd=SPIKE_ROOT,
        check=True,
    )
    inventory = json.loads(inventory_path.read_text())
    if inventory["source_set_sha256"] != fixture_source_digest(dirty_lane, paths):
        raise ValueError("Go AST inventory did not attest the dirty source set")
    dirty_ir_path = dirty_root / "syntax-ir-go.json"
    conformance = json.loads(subprocess.run(
        [
            "python3", str(SPIKE_ROOT / "scripts/compare_go_ir_inventory.py"),
            "--fixture", str(dirty_lane), "--inventory", str(inventory_path),
            "--ir", str(dirty_ir_path),
        ],
        capture_output=True,
        text=True,
        check=True,
    ).stdout)

    old_index_sha = sha256_file(clean_lane / "index.scip")
    old_recheck = subprocess.run(
        [
            "python3", "-B", str(code_ir_root / "scripts/code-ir-shadow-recheck.py"),
            "scip-go", str(dirty_root), "go", str(SPIKE_ROOT), f"sha256:{old_index_sha}",
        ],
        cwd=code_ir_root,
        input=dirty_ir_path.read_text(),
        capture_output=True,
        text=True,
        check=False,
        env={**os.environ, "PYTHONDONTWRITEBYTECODE": "1"},
    )
    stale_error = (old_recheck.stderr + old_recheck.stdout).strip()
    if old_recheck.returncode == 0 or "stale full selected source set" not in stale_error:
        raise AssertionError(f"old SCIP snapshot was not rejected for changed source: {stale_error}")

    fresh_index = dirty_lane / "fresh-index.scip"
    indexed = subprocess.run(
        [
            str(binary), "index", "./...", "--module-root", ".",
            "--repository-remote", "synthetic/workflow", "--module-version", "fixture-v1",
            "--skip-tests", "--output", fresh_index.name,
        ],
        cwd=dirty_lane,
        capture_output=True,
        text=True,
        check=False,
    )
    if indexed.returncode != 0:
        raise RuntimeError(indexed.stderr or indexed.stdout)

    sys.path.insert(0, str(dirty_root))
    import scip_pb2  # generated by the earlier isolated schema step

    index = scip_pb2.Index()
    index_bytes = fresh_index.read_bytes()
    index.ParseFromString(index_bytes)
    documents = {document.relative_path: document for document in index.documents}
    if set(documents) != set(paths):
        raise AssertionError("fresh dirty SCIP index selected a different document set")
    encodings = {path: document.position_encoding for path, document in documents.items()}
    if set(encodings.values()) != {1}:
        raise AssertionError(f"fresh custom index did not declare UTF-8: {encodings}")

    valid_primary = 0
    valid_definition_enclosing = 0
    enclosing_present = 0
    for relative, document in documents.items():
        raw = (dirty_lane / relative).read_bytes()
        text = raw.decode("utf-8")
        for occurrence in document.occurrences:
            start, end = range_bytes(text, occurrence, 1)
            if not (0 <= start < end <= len(raw)):
                raise AssertionError(f"invalid primary byte range: {relative} {start}:{end}")
            raw[start:end].decode("utf-8")
            valid_primary += 1
            if occurrence.symbol_roles & 1 and (
                occurrence.enclosing_range or occurrence.WhichOneof("typed_enclosing_range")
            ):
                enclosing_present += 1
                left, right = range_bytes(text, occurrence, 1, enclosing=True)
                if left <= start < end <= right:
                    valid_definition_enclosing += 1

    shutil.copyfile(fresh_index, dirty_lane / "index.scip")
    fresh_recheck = subprocess.run(
        [
            "python3", "-B", str(code_ir_root / "scripts/code-ir-shadow-recheck.py"),
            "scip-go", str(dirty_root), "go", str(SPIKE_ROOT),
            f"sha256:{sha256_file(fresh_index)}",
        ],
        cwd=code_ir_root,
        input=dirty_ir_path.read_text(),
        capture_output=True,
        text=True,
        check=False,
        env={**os.environ, "PYTHONDONTWRITEBYTECODE": "1"},
    )
    fresh_rejection = (fresh_recheck.stderr + fresh_recheck.stdout).strip()
    if fresh_recheck.returncode == 0 or "stale full selected source set" not in fresh_rejection:
        raise AssertionError(f"fixture-pinned importer did not identify dirty snapshot: {fresh_rejection}")

    result = {
        "schema": "scip-go-dirty-snapshot-probe-v1",
        "fixture_id": "go-workflow-discovery-v1",
        "clean_source_set_sha256": source_before,
        "dirty_source_set_sha256": source_after,
        "dirty_fixture_source_sha256": inventory["source_set_sha256"],
        "changed_path": "internal/discovery/state.go",
        "unchanged_referrer_path": "internal/selection/validator.go",
        "unchanged_referrer_sha256": reference_sha_after,
        "old_scip_artifact_sha256": old_index_sha,
        "stale_old_join_rejected": True,
        "stale_rejection": stale_error.splitlines()[-1],
        "fresh_scip_artifact_sha256": sha256_file(fresh_index),
        "fresh_fixture_pinned_join_rejected": True,
        "fresh_fixture_pinned_rejection": fresh_rejection.splitlines()[-1],
        "fresh_documents": len(documents),
        "declared_position_encodings": sorted(set(encodings.values())),
        "valid_primary_source_spans": valid_primary,
        "definitions_with_enclosing_range": enclosing_present,
        "valid_definition_enclosing_spans": valid_definition_enclosing,
        "dirty_ir_snapshot_id": json.loads(dirty_ir_path.read_text())["snapshot"]["snapshot_id"],
        "independent_go_ast_unit_matches": conformance["exact_span_kind_and_token_matches"],
        "go_ast_units": conformance["inventory_units"],
        "scip_binary_sha256": sha256_file(binary),
        "note": "The fixture-pinned SCIP importer intentionally rejects the dirty generation; the fresh build was checked for complete file coverage and source-byte ranges, not promoted as a production join.",
    }
    report_path = work / "freshness-report.json"
    report_path.write_text(json.dumps(result, indent=2) + "\n")
    return result


def fixture_source_digest(root: Path, paths: list[str]) -> str:
    digest = hashlib.sha256()
    for relative in sorted(paths):
        digest.update(relative.encode("utf-8"))
        digest.update(b"\0")
        digest.update((root / relative).read_bytes())
        digest.update(b"\0")
    return digest.hexdigest()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--clean-root", type=Path, required=True)
    parser.add_argument("--fixture", type=Path, required=True)
    parser.add_argument("--code-ir-root", type=Path, required=True)
    parser.add_argument("--scip-go-binary", type=Path, required=True)
    parser.add_argument("--work-dir", type=Path, required=True)
    args = parser.parse_args()
    print(json.dumps(run(args), indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
